### ISSUE TITLE
Java9 modules (Jigsaw) support

### ISSUE THREAD

**Issue by nemphys** [cache2k/cache2k#109]
Hi, I am wondering if there is any intention to support Java 9 modular setups by introducing module-info.java file(s) in the near future.

**Comment by cruftex** [comment]
We don't feel much "pressure" here, since we don't need it for our own projects right now.

But its good that you opened an issue, so we will consider this on our next cache2k enhancement sprints. Anybody else needs/wants this?

**Comment by claudio-rosati** [comment]
I would like it too.
In the meanwhile adding the automatic module name in the manifest could be an initial compromise:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <version>3.1.2</version>
  <configuration>
    <archive>
      <manifestEntries>
        <Automatic-Module-Name>se.europeanspallationsource.javafx.control.knobs</Automatic-Module-Name>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
```

**Comment by cruftex** [comment]
@claudio-rosati, good point. Just read about that, here: http://branchandbound.net/blog/java/2017/12/automatic-module-name/

I'll add that to the last stable version and release it the next days.

**Comment by cruftex** [comment]
Info on how to maintian Java 8 compatibility but add module information:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html

**Comment by cruftex** [comment]
@claudio-rosati, I just released version 1.2.2.Final which includes the manifest entry in the api jar.

**Comment by claudio-rosati** [comment]
Thank you

**Comment by cruftex** [comment]
I plan to "do this right" for the 2.0 version, since this requires some more restructuring.

Some thoughts:

In https://github.com/cache2k/cache2k/issues/80 we did collapse optional features (configuration and JMX support) into a single jar. With proper Jigsaw support I tend to reverse that decision, since a single jar would need to include more dependencies that are actually needed. I think separate that modules again, but, for a good OOTB experience and transitioning make cache2k-core depend on them. For a more minimal build one could then simply exclude these optional dependencies.

I tend to keep the separate API jar. Jigsaw allows us to specify the public API, but we still want to be compatible with Java 8.

**Comment by cruftex** [comment]
Relevant jars fully modularized, delivered in preview 1.9.1.Alpha, see: https://github.com/cache2k/cache2k/releases/tag/v1.9.1.Alpha
