### ISSUE TITLE
Generic types and type information for cache construction

### ISSUE THREAD

**Issue by tburny** [cache2k/cache2k#11]
Although there is a special method for building caches with collections as value, the available pieces of information are not used when building the cache

For example
  Cache<String, Set<SeenItem>> userToItemCache =
    CacheBuilder.newCache(String.class, Set.class, SeenItem.class)
      .expirySecs(30 * 60)
      .build();

This would return a `Cache<String, Set>`, although it would be much better to return a `Cache<String, Set<SeenItem>`.

Maybe there can be a special buildCollectionCache() method 

      public abstract <C extends Collection<T>> Cache<K, C<T>> build(Class<C> _collectionClass);

which simply uses `build()` and casts the result accordingly? This helps to prevent boilerplate code, as it is a common use case to have Collections as values.

**Comment by tburny** [comment]
Probably the CacheBuilder can be modified so that explicit type hints and Class.cast(Object) can be used to guarantee type safety, as in Bloch's "effective java".

**Comment by cruftex** [comment]
I tried ;)

Actually the type should be transported at compile time via the CacheBuilder, which should be CacheBuilder, so the special build method is not needed. However the construct Cache<K, C<T>> or CacheBuilder<K,C<T>> is not working.

The additional collection type in the configuration is actually for some future extensions for the storage, so the cache can choose a better marshaller. I don't know if any other cache does have something like this. In JSR107 it is just a single type for the value also.

Any concrete code suggestions appreciated, other wise I would close this.

**Comment by ben-manes** [comment]
You probably want to use a [TypeToken](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/reflect/TypeToken.html) to capture the value and its generic type(s). That technique has a long history of success in DI containers (like Guice) and serializers (like Gson, Jackson, and even Jax-rs). I think Scala's manifests / type-tags worked similarly, since its all about a byte code hack to reify the type.

For a cache the type information seems to be of value only for serialization scenarios. As most common (and basic) usages are on-heap, its not buying much over erasures. For other tiers a pluggable serialization scheme is reasonable, so it seems better to leave that complexity to the serializer than the cache builder. Nothing doesn't guard too strongly against runtime errors, so reifying does not carry its conceptual weight (IMHO). I don't think JSR-107 did itself any favors with that API either, since its even harder to constrain types based on configuration files.

**Comment by cruftex** [comment]
@ben-manes:
 
Thanks Ben! That is a neat trick and works pretty well. Here is the how we do it:

    class ValueTypeToken<T> {
       protected ValueTypeToken() { }
    }

    class CacheBuilder<K, V> {
         static <K, T> CacheBuilder<K, T> newCache(
            Class<K> _keyType, ValueTypeToken<T> vtt) { ... }
    }

In action:

     Cache<Long, List<String>> c =
          CacheBuilder.newCache(Long.class, new ValueTypeToken<List<String>>() {}).build();

If needed, the cache can extract all type information from the anonymous class.

> For a cache the type information seems to be of value only for serialization scenarios.

There is some preliminary support for storage and off-heap in cache2k, which requires serialization. I am not sure whether I finalize it or throw it out and concentrate on other things first. At least, I'd like the API to be as future proof as possible.

> For other tiers a pluggable serialization scheme is reasonable, so it seems better to leave that complexity to the serializer than the cache builder.

Yes, others do so, but it violates the fundamental design principles of cache2k. 

  * *ease of use*: The cache should be enabled to find a proper serializer by knowing what types are involved, additional configuration of a specific serializer should be optional.
  * *fail fast*: By knowing the type(s) the cache is enabled to store and compare meta data to see whether class versions still fit and give warnings early.

**Comment by cruftex** [comment]
Naming: Should we stay with ValueTypeToken or reduce it to TypeToken? Any other ideas?

**Comment by cruftex** [comment]
It is now named CacheType<T>. Code is just committed. 

The actual interface is defined in CacheTypeDescriptor<T> which also provides a bean only structure to represent the type information.

You can build a cache now with:

      CacheBuilder.newCache(String.class, new CacheType<List<String>(){}).build()

**Comment by frgomes** [comment]
I was using TypeToken in a library.
I was able to understand the concept (and even wrote an [article](http://rgomes-info.blogspot.co.uk/2013/12/using-typetokens-to-retrieve-generic.html) on that) but other developers and users of the library never really liked it. They usually forgot to add the open/close braces after the call. This leaded us to abandon TypeToken for the benefit of clarity.

**Comment by cruftex** [comment]
The only way I found to get the correct compile time types on a collection value is:

    Cache<Long, List<String>> c =
      (Cache<Long, List<String>>) (Object) CacheBuilder.newCache(Long.class, List.class).build();

Since the builder returns a Cache<Long, List> you cannot even cast it to a Cache<Long, List<String>> directly. But then the cache only knows of the List, not List<String>.

**Comment by ben-manes** [comment]
Other than type tokens, the other approach is to inspect using a class's [getGenericInterfaces](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getGenericInterfaces--), [getGenericSuperclass](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getGenericSuperclass--), or a method's [getGenericReturnType](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html#getGenericReturnType--).

That's how most library's need of TypeToken is mitigated to special cases. For example Guice's Provider methods instead of an explicit binding using a type literal. This is all using the same technique set of techniques, of course, but hidden better. Since this is only needed for serialization, you might do something like,

```java
interface Serializer<K, V> { ... }
abstract class JavaSerializer<K, V> implements Serializer<K, V> { ... }

Cache<Long, List<String> cache = CacheBuilder.newBuilder()
    .persists(new JavaSerializer<Long, List<String>>() {})
    .build();
```

Then `persists` can use the serializer's explicit types captured within the serializer's class hierarchy. The builder can use erasures for on-heap only usage. This would have the same usage caveats as Guava's TypeToken describes, but would make it a little more seamless by gradually adding complexity only when certain features are requested.

**Comment by cruftex** [comment]
Ben, if you do not specify the types within the builders arguments, the only way to construct a cache is:

    //noinspection unchecked
    Cache<Long, List<String> cache = 
        (Cache<Long, List<String>>) CacheBuilder.newBuilder().build();

That is working right now. However, I am not sure whether I really want to support this. Please consider that there are other uses for known types. A brainstorming list:

 - The cast is ugly
 - An optimized cache (in heap!) implementation can be chosen, especially for int and long keys
 - type checking can be enforced at will, e.g. for testing and in sensitive environments
 - automatically generated cache names can include the type
 - the type is accessible via JMX, so ops guys see its a Cache<String, HtmlTile>

So, I have a strong tendency to kick out the type less cache construction. If really needed, the user can specify Object.class, if she really wants to store anything.

**Comment by ben-manes** [comment]
I'm not sure why you think that the cast is required. It works fine for both Guava and Caffeine. It just takes a little care chaining the build methods.

```java
// compiles with erasures
Cache<Long, List<String>> cache = Caffeine.newBuilder().build();
```

I agree that it cannot capture primitive types until Java 9's value types or reified object types without the language's help. Scala and other JVM languages have compiler support, but Java requires other workarounds or punting until the Java architects provide a clean mechanism.

**Comment by cruftex** [comment]
Ah, thanks. I somehow got stuck in my thinking with my passing the types from the top, instead of from the return type. That's a crispy cache construction.

It eliminates one of my five arguments :)

**Comment by cruftex** [comment]
Hmm, the most direct approach could be to use the builder itself as type capture, leading to:

    Cache<Integer, String> cache = new TypedCacheBuilder<Integer, String>(){}.build();

**Comment by cruftex** [comment]
Changed the builder interface to allow this directly. Starting with 0.25, the following pattern is the preferred way to use the builder:

````
     Cache<Long, List<String>> c =
       new Cache2kBuilder<Long, List<String>>() {}
         .name("myCache")
         .eternal(true)
         .build();
````

To allow smooth transition I introduced a new builder class `Cache2kBuilder`. The old builder class is still available, but will be removed in subsequent releases.
