### ISSUE TITLE
Usecase: Dynamic cache creation / IllegalStateException: Cache already created

### ISSUE THREAD

**Issue by vishalkmr304** [cache2k/cache2k#124]
In parallel world if multiple threads are trying to create the same cache. One succeeds and one fails with the exception(IllegalStateException). Is there any way so that another thread returns the cache which was created by earlier thread instead of throwing an exception. I have a workaround to catch exception and do the same. Is it by design or we can have control if cache exists while creating it returns the cache(maybe some sort of feature or something?). Just a thought.

**Comment by cruftex** [comment]
Thanks for raising the issue. Its always good to have some additional viewpoints.

If you create the same cache twice, this can mean:

1. You like to have the identical cache
2. The service that is creating the cache is accidentally created twice
3. There is a naming conflict. It should be two different caches but they have identical names

Typically caches are created in some initialization phase that is meant to be only run once. Any container (Spring, Guice, etc.) is taking care of that. If you don't use a container, you can use a singleton pattern, or request the cache in the class constructor (which isn't nice..).

Considering the above I decided to throw an exception and not proceed, because it is most 
likely that something is wrong.

Returning the identical cache when `CacheManager.createCache` or the `Cache2kBuilder` is used, might be a possibility, however, it is leading to all sorts of problems. For example, it needs to be checked whether the configuration is really identical and it still could be a mistake.

I think, it is also better to explicit and clear semantics. `createCache` should behave as named and not do some magic.

There is also `CacheManager.getCache()`. Currently it only returns a cache, when it was created before. If you don't use the programmatic configuration, it might be worth to discuss whether it should create the cache under the hood, if it is configured.

So, that's about the rationale behind it.

Can you share an example code snippet how you create and use the cache? Then we can see what's the best way.

**Comment by cruftex** [comment]
@vishalkmr304 ping!

**Comment by vishalkmr304** [comment]
Hi,
My use case is many independent entries wants to create the same cache (cacheName is same), my caching is done on the parameters of API, In case two simultaneous and independent request comes one wins over the other and one hangs in between. I agree to the point that cache should only be created once, but i want to keep/create cache dynamically and based on the requests, sometimes while starting up the container i might not know how many cache should i create. I would want them to be created as the requests comes. One way is to catch the particular exception and return the same cache it was trying to create. Thoughts ?

**Comment by cruftex** [comment]
From your description I assume you have a REST service like this one:

````java
@GET
@Path("{type}/{id}")
public Response getResource(@PathParam("type") String type, @PathParam("id") String id) {
          .....
}
````

And you like to create separate caches for each requested type.

The KISS approach is to not do it and put all in one cache. This is done via a composite key of type and id. See the user guide: https://cache2k.org/docs/latest/user-guide.html#composite-keys

The other approach to create caches dynamically as you intended. Here is an example with `ConcurrentHashMap`:

````java
private final Map<String, Cache<String, String>> map = new ConcurrentHashMap<>();

public String getResource(String type, String id) {
  return map.computeIfAbsent(type, this::buildCacheForType).get(id);
}

private Cache<String, String> buildCacheForType(final String type) {
  return new Cache2kBuilder<String, String>() {}
    .loader(key -> getResourceInternal(type, key))
    .name("type-" + type)
    // more cache configuration
   .build();
}

private String getResourceInternal(String type, String id) {
  // expensive operation
}
````
`ConcurrentHashMap.computeIfAbsent` will make sure that the cache is only created once.
For this to work your service class needs to be a singleton, e.g. via the `@Singleton` annotation if you use JAX-RS. Alternatively you could make the map static, to ensure there is only one.

Be aware that this is an example. For production code you need to check the incoming type parameter, otherwise you allow everyone to create an infinite amount of caches.

**Comment by cruftex** [comment]
A different approach is to use the cache itself. Then you could use the cache expiry to remove an unused cache again. This is not yet working in cache2k 1.2, since you would need a synchronous expiry listener. I will add that in version 1.4. Here is the idea of the code:

````java
Cache<String, Cache<String, String>> type2Cache =
  new Cache2kBuilder<String, Cache<String, String>>() {}
    .name("type2Cache")
    // TTI emulation: expires an entry after 5-10 minutes after last access
    .refreshAhead(true)
    .expireAfterWrite(5, TimeUnit.MINUTES)
    // remove the cache, after no access comes in.
    // Attention: In cache2k 1.2 the expiry listener is always called asynchronous.
    // This creates a race condition with creating a new cache of the same type
    // Use this after cache2k 1.4 is released.
    .addListener((CacheEntryExpiredListener<String, Cache<String, String>>)
      (cache, entry) -> entry.getValue().close())
      .loader(new AdvancedCacheLoader<String, Cache<String, String>>() {
        @Override
        public Cache<String, String> load(
          final String type, long currentTime,
          CacheEntry<String, Cache<String, String>> currentEntry) {
            // TTI emulation: on expire we just return the same entry.
            // this will stay in the cache for 5 minutes more (probation period of refresh ahead)
            // and then expire, if no more requests go to this entry
            if (currentEntry != null) { return currentEntry.getValue(); }
              return buildCacheForType(type);
            }
        })
      .build();

public String getResource(String type, String id) {
  return type2Cache.get(type).get(id);
}
````

**Comment by cruftex** [comment]
Hi @vishalkmr304! I hope the question is answered. Any further questions or feedback is welcome.
