### ISSUE TITLE
Compare caffeine

### ISSUE THREAD

**Issue by Y-StrongBless** [cache2k/cache2k#126]
Compare caffeine, what is it advantages and disadvantages ?

**Comment by cruftex** [comment]
Thanks for the request. I'd like to add a comparison chart to the user guide some time in the future.
To be generic and fair, this will be quite a long list of features. So its difficult to give you a short answer here.

What is your application domain?

**Comment by cruftex** [comment]
This is dangling for a while, since it is hard to answer briefly and both projects are constantly in flow.
Anyhow I try to write down a kind of momentary snapshot:

Caffeine and cache2k have a similar feature set. Both are in-memory Java caches. 
The basic design approach is different. Caffeine is a pure library with a quite narrow scope.
Cache2k has a more broader scope and tries to solve typical caching problems as one stop shop, e.g.
by having support for exception handling (or resilence features). However, that beeing said, cache2k 
is a compact library, the actual jar size of cache2k is around 400kB and Caffeine around 860kB.

## Why you don't want to use cache2k (right now)

Rather then start with praise for cache2k, I think its better to start with where cache2k is currently lacking:

- missing expiry after access / time to idle. See [GitHub issue #39](https://github.com/cache2k/cache2k/issues/39)
- adaptive cache eviction makes Caffeine adapt better to some workloads, see [GitHub issue #101 - Adaptive Eviction](https://github.com/cache2k/cache2k/issues/101)
- Caffeine has an `AsyncLoadingCache` based on `CompletableFutures`. cache2k has async support but different interfaces. More work on async interfaces needs to be done, see [Async cache API ideas and discussions](https://github.com/cache2k/cache2k/issues/144)
- Caffeine uses `ConcurrentHashMap`. `ConcurrentHashMap` can fall back to a tree structure if hash codes procuce conflicts but only if the key class implements `Comparable`
- Wrapping values or keys into `WeakReferences`. If somebody needs this, please open an issue

The usage of `ConcurrentHashMap` has pros and cons. Whether support `WeakReferences` is mandatory, I don't know. I am happy to discuss a scenario and user need and see whats a good approach.

For the other issues we plan enhancements in the near future.

## Important differences to Guava and Caffeine

While looking similar, there are some important differences that may be pitfalls.

Caches in cache2k are managed and can have a defined name. After usage a cache2k cache needs a `Cache.close()` while Caffeine caches would be garbage collected. Practically Caffeine caches should be "shut down" as well, e.g. via `Cache.clear()` to make shure that pending timers and tasks produce no memory leak. The use of a cache manage allows to provide features like external configuration, micro meter and JMX support. Controlled cache lifetime is also essential in case we want to add featres like persistence later, e.g. to flush unwritten data.

Caffeine uses `System.nanoTime()` as time base for expiry, while cache2k uses `System.currentTimeMillis()`.
Caffeine works with duration, while cache2k works with absolute times. Use of `System.currentTimeMillis()` and absolute times makes it possible to expire at a point in time, if business rules require this. So cache2k can be used as expiring map which is sychronized to the wall clock. Expiry after duration is supported in cache2k as well and very efficient. The time reference can be changed in both caches. Both implementations use a timer wheel for efficent expiry.

There is a slight difference in the interpretation of the concept of expiry. In Caffeine expiry means an entry become invalid and is consequently removed from the cache. In cache2k it means the entry is not valid any more and, in case of read through operation with a `CacheLoader`, which is very common, it needs to be fetched again from its origin. Expired entries can be refreshed in cache2k and the data can be kept (optionally) after expiry and reused in the cache loader to optimize the update, e.g. to issue and `if-modfied-since` request.

## Why you want to use cache2k

cache2k is a highly efficient in memory cache with low memory overhead and high throughput. Cache2k outperforms Caffeine by a factor of two or more for cache friendly workloads, see the latest [benchmarks](https://cache2k.org/benchmarks.html)

cache2k has a concise API that is provided in a separate module. The `Cache` interface is complete and contains all methods needed for efficient cache interaction. This interface is adapted from the JCache standard and allows the future extention towards hierachical caching. In Caffeine or Guava cache clients must use a mixture of a `Cache` and a `Map` interface and is efficient for in memory cache implementations only. For easy portability cache2k supports the map view as well. In some sense the cache2k API is a cleaned up version of the JCache API.

At the time of writing, looking at the current feautre requests of Caffine, cache2k has already 
integrated solutions for two of them, which is [Variable refresh](https://github.com/ben-manes/caffeine/issues/504) and (bulk refresh)[https://github.com/ben-manes/caffeine/issues/7].

Integrated and out of the box support for cache statistics with micro meter and JMX. In cache2k  this can be enabled via configuration. In Caffeine this needs additional glue code. For example, you can use Caffeine as a hibernate cache via JCache, but you cannot enable statistics export via configuration.

Cache2k has a bunch of features not available in Caffeine, that help to build low latency and resilient applications. Here are some differences which come to my mind:

- Cache2k is doing retries automatically after a loader exception with an exponential back off. The resilience behavior, meaning what to do with exception is completely customizable, see: https://cache2k.org/docs/latest/user-guide.html#resilience
- It is possible to do point in time expiry synchronized to the system clock in cache2k. This allows the cache to be used as an elegant expiring map which does recalculations needed at some point in time
- cache2k tries to be user friendly and do the reasonable and conservative things to be usable out of the box without too much or any configuration. Cache2k has a resonable low default capacity limit while a Caffeine  cache is unbounded by default. Caffeine has a `cleanUp()` method on the Cache interface. It is not totally clear when and whether this method needs to be called. Whilte it typically does not need to be called its existence is confusing. cache2k has no such thing and as a design principle will not have it
- Complete set of listeners (create, update, delete, evict, expire, cache lifetime)
- Cache2k has an integrated configuration system either programatically or by file
- Extensions can be added by configuration, e.g. enable statistics or wrap all caches and add extra functions
- In Caffeine a refresh is triggered when an entry is accessed after the refresh interval. In cache2k a  efresh is a "refresh ahead", meaning the refresh starts when the entry is considered as expired. The semantic of cache2k aligns with usiness requirements like "it takes a maximum of three minutes for data updates to become visible"
- The refresh time can be variable in cache2k and is controlled via the ExpiryPolicy, in Caffeine it is static  
- `Cache.clear()` doesn't block in case entries are processing (e.g. because of a load). This sacrifies linearizability of entry operation, in favor of a fast clear not blocking the whole application because of single operations are in flight. Cache2k alternatively has `Cache.removeAll()` which honors linearizability of entry operations and also calls removal listeners
- An `AdvancedCacheLoader` makes the current entry available allowing to optimize update requests
- Delta expiry: Expiry durations can be calculated based on the changes between the previous data value
- An async bulk loader can return partial results and individual expections per key. This is useful since the request might get split or joined (in case of the coalescing)
- Bulk load operations are blocking. Caffeine drops blocking semantics for bulk requests for the synchronuous implementation, which means multiple requests to the same key may be sent by Caffeine. Blocking bulk requests are tricky, because as soon as you block on multiple entries potential deadlocks need to be avoided  
- A coalescing bulk loader is available   
- To be fast Caffeine uses queues and executors to do maintenance tasks, for example for eviction. This is good for interactive workloads and makes potentially better use of available CPU resources. In throughput operations, the workload uses all CPU resources, usually by using the same amount of threads than CPUs. In this scenario Caffeines maintenance tasks compete with workload trheads

At some point there should be a more structured comparison. Probably I put some feature comparison tables in the documentation. Although this is still biased by me, everybody can open pull requests and correct and extend.
