### ISSUE TITLE
License & commercial projects

### ISSUE THREAD

**Issue by ocafebabe** [cache2k/cache2k#13]
Hello,

Is it possible to use this library in a commercial (closed source) project?

Thanks

**Comment by cruftex** [comment]
Very good point, thanks for addressing this.

cache2k actually uses the GPL license. The GPL license is more restrictive then, for example, the Apache license. However, the GPL license does not mean that you need to make the source of your product available publically, but, you need to make the source available to everyone that gets the product from you.

Since we ship always source and binaries to our costomers, this is essentially perfect in our business.

I am aware that the GPL may not work for anyone and a less restrictive license may be needed. The GPL licensing also makes it impossible to integrate cache2k within Apache projects.

Since GPL is okay for our business, cache2k is released under GPL at the moment.

Depending on the demand this will change in future, so:

If there is interest by other open source projects to integrate cache2k, but they need a different license. Please comment on this issue.

If there is interest in using cache2k in a product, that licensing would conflict with GPL, pls. contact me and tell me what features of cache2k you intent to use in what scenario (server, android app, number of users, etc.), plus, whether and what competive advantage you might have in contrast to use other caching products. Then we look for a solution that fits your needs. I could issue a separate license, restricted to a product, but unrestricted in any other way. Alternatively, I could release parts or everything of cache2k under a different license.

**Comment by cruftex** [comment]
If needed, please get in touch at: github@cruftex.net

**Comment by ocafebabe** [comment]
What I'm looking for is a simple in-memory cache for a JEE application. And I found your project on Stack Overflow: http://stackoverflow.com/questions/575685/looking-for-simple-java-in-memory-cache. At first I thought wow this would be a perfect fit for my use case!

But in my case we only ship binaries to our customers so the GPL is a no go. Something like the LGPL would be more appropriate for us...

**Comment by maciej-kapusta** [comment]
I really like this library. It is almost three times faster than Guava in our benchmarks. It would be really great if you released it under LGPL. I am not a lawyer, but I believe you can mix it with GPL for the rest of your code base.

**Comment by cruftex** [comment]
Good news, I finally decided to change the license to Apache. I will rerelease the last version and the release the next versions under the Apache license.

**Comment by cruftex** [comment]
Changed the sources to Apache license. Release version 0.23 as 0.23.1 Apache licensed.

**Comment by maciej-kapusta** [comment]
That is great new thank you.
__
Maciej Kapusta
Software Engineering Expert
www.codewise.com <http://www.codewise.com/>    

 <http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg4XX_D-W2zWYWz7fcJ5dVdVcBC56dMT0f4HV2VK02?t=http%3A%2F%2Fwww.voluum.com%2F&si=6137026973270016&pi=5468f37b-2a81-4fff-e536-028fe1915e18>     <http://www.zeropark.com/>
 <http://www.zeropark.com/>

**Comment by cruftex** [comment]
Put the general line of thinking in the blog post: http://cruftex.net/2016/04/07/cache2k-is-now-apache-licensed.html

**Comment by ocafebabe** [comment]
This is indeed really great news! Thanks a lot for this new license!
