### ISSUE TITLE
missing `close` method in `org.cache2k.core.timing.Scheduler`

### ISSUE THREAD

**Issue by dawnwords** [cache2k/cache2k#167]
**Version of Cache2k**：1.6.0.Final

`ClassLoader` leakage was detected in an hprof dumped by out of MetaSpace.

|Class Name  | Shallow Heap | Retained Heap|
|-------|-------|------------|
|contextClassLoader java.lang.Thread @ 0x6549784f8  cache2k-scheduler Thread|          120 |           344|
|contextClassLoader java.lang.Thread @ 0x6549787a0  cache2k-scheduler Thread|          120 |           344|

Seems that `Scheduler` does not contain `close` method causing `ScheduledExecutorService` leakage.

**Comment by cruftex** [comment]
Valid point, there is some room for improvement. It works well in our scenarios, so I kept it intentionally simple. Some explanation:

The `Schedule` interface has no `close()` method, since its actually backed by only one scheduler service for all cache instances. Each cache instance is only scheduling one task, that gets executed when the upcoming expiry needs to be processed.
There is also no method to cancel a scheduled task or reschedule. If another task is scheduled the previous one would fire and see that there is nothing to do. When a cache gets closed, the expectation is that the remaining task gets executed in the near future and the reference is cleared.

I can think of multiple ways to improve here. However, I don't want to make things more complex as needed.

@dawnwords, can you please briefly describe your usage scenario, so I can create and test improvements accordingly?

**Comment by dawnwords** [comment]
> @dawnwords, can you please briefly describe your usage scenario, so I can create and test improvements accordingly?

@cruftex Thank you for your immediate response. We use Cache2k when processing data stream in [Flink](https://flink.apache.org/) as a Global TTL-based Cache holding metadata sharing across different Processing Functions. Since Flink TaskManager seperates different Jobs with different `ClassLoader`s in Session Cluster Mode, a `ClassLoader` leakage happens if the coresponding Job starts some daemon Threads which holds the reference towards the `ClassLoader` but may not be closed when the Job is closed. As the Job starts and stops, the `ClassLoader` leakage accumulates causing JVM Out-Of-MetaSpace Error. 

In our case, we need to find out a way to stop all threads started by third-party libs when a Flink Job is closed. I did not trace into the source code of Cache2k. Is it safe just to shutdown `org.cache2k.core.timing.DefaultScheduler.INSTANCE` with **reflection** when closing the Job?

**Comment by cruftex** [comment]
Thanks for the explanation.

> Is it safe just to shutdown org.cache2k.core.timing.DefaultScheduler.INSTANCE with reflection when closing the Job?

You can, if all caches are closed within this class loader.

A possible solution would be reference counting, so we shutdown the threads when the last cache is closed.
Another solution would be to use a `ScheduledThreadPoolExecutor` from `CompletableFuture` implementation in the JVM.
That is possible with Java 9 and above, and, that is what Caffeine is doing. I prefer separate threads, which helps with pinpointing problems like this one.

I also decided to move the clock and scheduler interface to the public API, so its possible to change the implementation if needed.

You can expect an update for this in the next days.

Would it be possible to load cache2k with a common class loader in flink? It would be better not to start extra threads per Job.

What is your typical timeout duration?

Version 2.0 for cache2k is about to be completed. Most applications should need only minor changes for it. Can you check the latest prerelease (1.9.3.Alpha at the moment) and let me know whether you need a backport to 1.6 of the changes or whether you can proceed with 2.0. The next release would be probably 1.9.4.Beta, because I think I am almost done with the API changes now.

**Comment by cruftex** [comment]
@dawnwords: I just released [v1.9.4.Beta](https://github.com/cache2k/cache2k/releases/tag/v1.9.4.Beta) which destroys the threads after the last cache is closed. Although I did lots of API changes during 1.9.x which will be the upcoming 2.0 it will be still compatible to most existing code.

Let me know whether this works for you.

**Comment by cruftex** [comment]
@dawnwords: I hope you are well. Closing this issue since its fixed in head now.

There is still a potential leakage if there is expiry in the distant future and caches closed and created again.
My plan is to do another improvement, either cancel timer jobs and clear the reference or use a weak reference.
I'll do that in https://github.com/cache2k/cache2k/issues/24 since for this issue I specifically test with creating
and destroying lots of caches.

However, with the last fix it does not affect you since your jobs have a separate scheduler that gets shut down.
So I expect your scenario now to work perfectly.

Although its closed feel free to comment if you have feedback or we need to look into it again.
