### ISSUE TITLE
Github Sponsoring

### ISSUE THREAD

**Issue by coffeemicha** [cache2k/cache2k#190]
Hey @cruftex 

thank you for providing cache2k!
We are planning to use it in a pretty large project in my company, and I was wondering if you would like to setup GitHub Sponsoring so that we can support you a bit for doing your work.

Warm regards
michael

**Comment by cruftex** [comment]
Hi Michael,

thanks for reaching out! Sorry for the late reply. I will look into GitHub Sponsoring the next days.
It would be great to hear more about your use case, also. It always helps me to hear from happy users, so I have a better idea where to steer the project.

**Comment by cruftex** [comment]
The GitHub sponsor page is now active: https://github.com/sponsors/cache2k
If there is any feedback or idea, that's highly welcome.

@coffeemicha 
Since we are both located in Germany, it might be more efficient to use normal bank transfer, since otherwise there is service charges and money conversion twice, I assume.

Also, if you are happy with cache2k it would be great to put a brief description of your company and your usage somewhere on the webpage. And if you are not happy, I will fix it ;) Although I know of some big and heavy users, so far its all in the dark.

Closing the issue, since sponsoring is enabled now. However, feel free to comment further if you have any feedback or questions.
