### ISSUE TITLE
performance degrades ﻿ when using mutate() to implement expireAfterAccess

### ISSUE THREAD

**Issue by fightchwang** [cache2k/cache2k#209]
hi, there
thanks for the awesome tool, 
i'm using  `2.6.1.Final` cache2k to implement the so called `expireAfterAccess()` in other cache such as `caffeine`, as the demo:
https://github.com/cache2k/cache2k/blob/0eaa156bdecd617b2aa4c745d0f8844a32609697/cache2k-testsuite/src/main/java/org/cache2k/testsuite/example/TimeToIdleExampleTest.java#L50-L70

but faces performance degradation compared with the way using `get()` or `put()` .

the difference is significant.

can you guide me on how to fix this ?

btw, i also follow the `idleScan` way. but the active items(keep accessing by get()) in cache will also be evicted from cache..
like the issue https://github.com/cache2k/cache2k/issues/206 said.
seems there's no update on something like `lastAccessTime', right?

**Comment by fightchwang** [comment]
not an issue, my local env problem.

**Comment by cruftex** [comment]
Hi @fightchwang, sorry for the late response.

basically yes, the difference would be very significant. A get would be just a lookup and a read, the put, if the entry is already existing, might just be a lookup and a write.

If you update the expiry time, some data structures need to be updated, so multiple writes, locking and maybe even new objects. Also cache.mutate creates objects for its processing. That alone will make a significant difference.

If, as in this case, the expiry time is always increasing, the data structures could be optimised more. However, there would be always a significant difference remaining.

I also commented on #206.

Closing this one, since your observation is expected.
