### ISSUE TITLE
Always get error ,  Cache name contains illegal chars: '<', name="TaxCalculatorInstance.<clinit>.47"

### ISSUE THREAD

**Issue by liuhongze** [cache2k/cache2k#47]
Hi, I am trying to create a static field in my class Test.java as this,   

 public static Cache<String,String> idCache = CacheBuilder.newCache(String.class, String.class).build(); 

But when I create an instance of  Test.java, I got the exception.

Caused by: org.cache2k.impl.CacheUsageExcpetion: Cache name contains illegal chars: '<', name="TestInstance. <   c l init  > .47"
	at org.cache2k.impl.CacheManagerImpl.checkName(CacheManagerImpl.java:130)

I need to share this cache among all the instances of Test.java. So, I use static. 

I am confused now, not sure did I use Cache2K incorrectly ?

**Comment by cruftex** [comment]
Short version:

To solve your problem add `.name(Test.class)` before `build()`.

Long version:

Each cache needs to have a unique name for various organizational reasons, e.g. additional configuration that could be applied, registering the cache with JMX, listing active caches for debugging, etc.

But for testing, or, if you have a very simple application, there is actually not much use to
give every cache a proper name. For that reason there is some code in cache2k that derives
a useful name internally. This code fails for your example, if the cache is constructed in the
class constructor.

As a matter of coincidence I realized that problem yesterday also:
https://github.com/cache2k/cache2k/commit/2a18b4479ad1b16b7d0f69f7feedbec8430a5656

**Comment by cruftex** [comment]
Added a unit test. Your example will work, without setting a name explicitly, in the next release.
However, always setting a proper name is a good idea, so you can identify your caches.

Thanks for the bug report!

BTW:
I am aware of that starting with cache2k is pretty hard, since the documentation is pretty much non existent. Currently I am improving the JavaDocs and will start to write on a introduction document the next days. Feel free to ask more questions here or on stackoverflow as soon as you get stuck.
