### ISSUE TITLE
putIfAbsent does not set expiryDuration

### ISSUE THREAD

**Issue by erikermert** [cache2k/cache2k#48]
hi, while using Version 0.23.1 my monitoring showed that a cacheEntry inserted or updated with putIfAbsent() does not expire. Documentation doesn't indicate that. I assume it is a bug?

Example programm:
```		
Cache<String,String> testCache  = CacheBuilder.newCache(String.class, String.class).name("testCache").expiryDuration(3, TimeUnit.SECONDS).build();

testCache.putIfAbsent(Test.KEY, Test.VALUE);
for (int i =0; i <5; i++){
    TimeUnit.SECONDS.sleep(2);
    if (testCache.peek(KEY) == null){
        System.out.println("MISS");
        testCache.putIfAbsent(KEY, VALUE);
    } else {
        System.out.println("HIT");
    }
}
```
output: 
HIT
HIT
HIT
HIT
HIT

same Code with put instead of putIfAbsent:
output:
HIT
MISS
HIT
MISS
HIT

The second output is the expected one. :)

**Comment by cruftex** [comment]
I assume it is a bug, too. Will look into that.

**Comment by cruftex** [comment]
Yes, this bug is present in 0.23.1

The latest version 0.25-BETA works correctly. I fixed this without knowing of the problem, since I did strip and simplify the code base a lot.

In terms of functionality I consider the latest versions more mature then 0.23. I just marked them as BETA since I am doing some reorganizing of the API while working towards 1.0.

**Comment by erikermert** [comment]
thx. we will use 0.25 instead :)

**Comment by cruftex** [comment]
You are welcome. Thanks for reporting this issue.
