### ISSUE TITLE
Entry Weight Support / was: Limiting a cache by memory size?

### ISSUE THREAD

**Issue by io7m** [cache2k/cache2k#50]
Hello.

I'm evaluating various options for caching bitmaps in an imaging application. Is it possible to limit the size of a `cache2k` cache in bytes instead of by the number of entries? I'm loading lots of bitmaps of arbitrary unknown sizes, and so a cache of `100 * 1mb` bitmaps is obviously a very different creature to a cache of `100 * 100mb` bitmaps!

I can't seem to find anything in the API that would allow this, but perhaps I've overlooked something?

**Comment by cruftex** [comment]
There is no such feature in cache2k yet. I tinkered around various approaches, but then postponed it, since we had no real own need. Right now I'd like to finalize the features that are available in a 1.0 version (actually I urgently need to get back to it, I am currently a little hold up with other stuff).

I just take the chance to put down my thoughts on this.

### Use cases

In general I might want to instruct the cache to adapt in the following ways:

- Limit used memory, values have different and unpredictable sizes
- Limit used memory, values are homogeneous, used memory should be limited
- Limit the number of entries
- Cache(s) should use available memory efficiently (actually there is a max heap size MV parameter, why additional ones?)
- The cache should keep the response time within a limit

### Solutions

#### EHCache sizeof engine

Instead of a maximum entry count, you can configure a byte size limit. By using a byte size limit the cache changes its performance characteristics, since updating the cache involved analyzing the object instance and updating the used bytes. Without having done a benchmark yet, I would expect that the cache update is at least ten times slower with size limit. That depends on the value complexity. Determining the used space of a cached value, actually never works really reliable. You don't know whether an object e.g. a string is referenced by the cached value alone. You don't know the fragmentation overhead. The EHCache code depends on the attach API to do its calculations. That is documented and available on an Oracle JVM, but it is not a Java specification. I would prefer my application to be a Java application and not a Oracle JVM application.

It seems to me that people use the byte limit without really knowing all the implications. "bytes" seems to be a known concept, however, it is not totally clear what happens.

Also this seems a source of trouble, e.g.:
http://stackoverflow.com/questions/38107419/ehcache-threads-crashing-if-using-maxbyteslocalheap-and-maxbyteslocaldisk

#### Guava or Caffeine weighted values

You can specify a weigh method and a maximum weight. The cache needs to store an additional 8 bytes per entry. This IMHO preferable to the EHCache approach, since the runtime overhead is more predictable. AFIAK Caffeine is only needing the additional bytes per entry if weighting is used.

@io7m:
Think twice whether you really need it. Maybe you can go with a meaningful worst case or average size? Maybe you can cache more homogeneous tiles instead (compare to map tiles)?

If you really, really need it the weight feature of Guava or Caffeine is quite okay.

**Comment by cruftex** [comment]
@io7m:
Can you detail why the bitmaps are so different in size? In our applications I would usually what type of image is requested (thumbnail, small, big, icon, etc.), so one approach is simply use separate caches per image type.

**Comment by io7m** [comment]
Hello!

Mainly, I'm looking for a cache size limit as there's quite a bit going on in the application, we have a fixed heap size budget, and therefore know exactly how much of the heap can be dedicated to each subsystem.

In this case, the application is dealing with textures (which may be of any size but with the restriction that the width and height are less than or equal to 8192, and the width and height may be independent powers of 2), and arbitrary photos (which are a large range of "standard" photo sizes - 600 × 900, 1200 × 1800, etc).

**Comment by cruftex** [comment]
And what happens with those images/photos, so you need to keep the bitmaps in the heap?

Usually one would try to avoid those big objects in the heap. E.g. ImageIO is writing out temp files.

**Comment by io7m** [comment]
It's basically a streaming scenario. As the observer's moving around, textures and photos are being loaded and unloaded. Having a small in-memory cache between the GPU and the disk seems to improve visuals somewhat. We just don't want the cache to get too large.

**Comment by cruftex** [comment]
Hmm, keeping does bitmaps off heap or off screen inside the GPU seems to me preferable. You don't really need it inside the Java heap, since you don't really process them with Java.

Maybe Cassandras off heap cache is an option, too. See: https://github.com/snazy/ohc

**Comment by cruftex** [comment]
I added this a while ago, will be release with version 1.4
