### ISSUE TITLE
Get specific cache stats

### ISSUE THREAD

**Issue by espiegel** [cache2k/cache2k#53]
Hi,

I'm trying to get specific metrics from cache2k: hit rate, hit count, miss count, cache size etc. I want to feed these metrics into http://grafana.org/ so i can get a nice chart of the cache performance.

From what I could find in the documentation the only way to get this is to call `toString()` on the cache instance.

This means that I will need to parse the various metrics myself from a string. Is there a way to get the metrics separately?

**Comment by cruftex** [comment]
Hi Eidan,

interesting, I knew I have to write something about statistics and JMX :)

Yes, you shouldn't use the `toString()` output, since this is not a stable API. Maybe I will even shorten it radically, since it is quite verbose.

If you use the `cache2k-all` artifact you have JMX-Support. You can access the metrics via JMX. The available values are documented here: `https://github.com/cache2k/cache2k/tree/master/jmx-api/src/main/java/org/cache2k/jmx`. The object name of a cache is: `org.cache2k:type=Cache,manager=...,name=...`

I just saw, that I did some renaming of the JMX properties just after the last release (0.28-BETA). The next days I will release 1.0-RC1. That means no more renaming and the API keeps stable.

Internally cache2k has some more statistics, you can access them via `((InternalCache)cache).getInfo()`. This interface may change without notice, however, if there is a need to expose some more metrics, let me know.

**Comment by espiegel** [comment]
Thank you for the fast reply. `((InternalCache)cache).getInfo()` works. Any reason why it shouldn't be a publicly exposed on the cache interface?

I found that calling `cache.put(key, value)` on a freshly initialized cache will actually generate a cache miss. Looking at the code I think its because `put` will check if the item is in the cache or not first. I think this is wrong.

**Comment by cruftex** [comment]
> I found that calling cache.put(key, value) on a freshly initialized cache will actually generate a cache miss. Looking at the code I think its because put will check if the item is in the cache or not first. I think this is wrong to record this as a miss.

Sure? How to reproduce? The test is in `BasicCacheOperationsTest`:

````
  @Test
  public void put() {
    cache.put(KEY, VALUE);
    statistics()
      .getCount.expect(0)
      .missCount.expect(0)
      .putCount.expect(1)
      .expectAllZero();
    assertTrue(cache.containsKey(KEY));
    assertEquals(VALUE, cache.get(KEY));
    assertEquals(VALUE, cache.peek(KEY));
  }
````

**Comment by cruftex** [comment]
> Thank you for the fast reply. ((InternalCache)cache).getInfo() works. Any reason why it shouldn't be publicly exposed on the cache interface?

Because this interface reveals implementation details, that are not guaranteed to be exactly the same in the next release. Everything you expose, you cannot take away any more without breaking applications. 

Maybe there will also be a "lighter" version without statistics or just parts of them. That is why I want to keep the official API focused on its main purpose.

**Comment by espiegel** [comment]
Could be a mistake on my part, I will take a look at `BasicCacheOperationsTest` and will try to reproduce.

**Comment by espiegel** [comment]
Maybe its because I used `getInfo()` instead of `getLatestInfo()`.

**Comment by cruftex** [comment]
Added a documentation section on statistics:
https://github.com/cache2k/cache2k/blob/master/documentation/src/docs/asciidoc/user-guide/sections/_statistics.adoc
