### ISSUE TITLE
Add support for isStoreByValue in JMX

### ISSUE THREAD

**Issue by tonyfalabella** [cache2k/cache2k#62]
If possible can you please add support to the CacheInfoMXBean (or CacheManagerInfoMXBean) for at least showing the isStoreByValue attribute for caches implementing the JCache API?

Ideally if this can be updated from JMX too that would be great.  I know that EhCache shows this in the JMX console.

**Comment by cruftex** [comment]
`CacheInfoMXBean` is the JMX bean that is present for each cache instance. This will show up by default if not disabled and when you include the JMX support (its included in `cache2k-all` artifact).
However, on this level the cache doesn't know about store-by-value. These semantics are added "on top" by the JCache support.

There is the JMX bean `CacheMXBean` defined by JSR107/JCache which has `isStoreByValue`.
This JMX bean will only show up, when statistics are enabled via the JCache configuration (e.g. `CompleteConfiguration.isStatisticsEnabled`). Can you use that?

> Ideally if this can be updated from JMX too that would be great.

Why you need to update that value?

**Comment by tonyfalabella** [comment]
Ok I see what you mean @cruftex .  Yes I can use that.  

As for updating the value via JMX I think that's not needed (only use case for me was to see performance with and without it turned on "on-the-fly" without restarting my app).

**Comment by cruftex** [comment]
> As for updating the value via JMX I think that's not needed (only use case for me was to see performance with and without it turned on "on-the-fly" without restarting my app).

An on the fly change is technically not possible. If store by value is enabled, the cache is wrapped and on any call to the cache key and value objects will be copies as needed.

If you mind about performance, you shouldn't use store by value. Personally I think the parameter in the JSR107 configuration object is not a good idea, at all. See some general discussion about that here:
https://stackoverflow.com/questions/42772288/javax-cache-store-by-reference-vs-store-by-value

Please also mind that as soon as you specify a cache2k configuration, which probably everyone does, since the JSR107/JCache configuration is not sufficient, the setting `Configuration.isStoreByValue` gets ignored by default. See the discussion in the documentation chapter about that:
https://cache2k.org/docs/1.0/user-guide.html#jcache

Honestly, I have no idea instantly, what the JMX value reports in this case.

I know there is a lot of potential for confusion here. If still in doubt open another issue or a stackoverflow question. I'd be happy to learn more about you use case.
