### ISSUE TITLE
Custom map backend support

### ISSUE THREAD

**Issue by dave08** [cache2k/cache2k#69]
Wouldn't it be a good idea to provide some kind of interface to implement and set the cache map backend? It could help in integration with other libraries, like vert.x sharedData and clusteredSharedData. Or maybe that might not be good for perfomance...?

**Comment by cruftex** [comment]
> Or maybe that might not be good for perfomance...?

Yes, it won't be good for performance. One reason cache2k is performing better as other caches, since it comes with a specialized map implementation for that job.

> Wouldn't it be a good idea to provide some kind of interface to implement and set the cache map backend?

The idea is not bad, but not trivial or even impossible. You cannot support all the functionality a cache in cache2k has, on top of a simple map. For instance, where and how do you store the data for the eviction algorithm?
