### ISSUE TITLE
API changes review for Cache2k

### ISSUE THREAD

**Issue by lvc** [cache2k/cache2k#70]
The review of API changes for the Cache2k library since 0.19.1 version: https://abi-laboratory.pro/java/tracker/timeline/cache2k-api/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-compliance-checker tool.

Thank you.

![cache2k-api-2](https://user-images.githubusercontent.com/1517837/31003460-809e182e-a4f8-11e7-988b-f63af85951a4.png)
![cache2k-api-1](https://user-images.githubusercontent.com/1517837/31003461-809e887c-a4f8-11e7-9942-4254cfeeebd1.png)

**Comment by cruftex** [comment]
That is very cool. I'll keep the issue open, because I want to put a link somewhere in the documentation or website.

**Comment by cruftex** [comment]
@lvc Hi Andrey,

I am just preparing version 1.2 of cache2k. Since I know I do a very tiny bit of non binary compatible changes I checked the report of your tool.

Unfortunately it lists a lot of incorrect things. For example:

- Removed method `DefaultCustomizationCollection<T>.clear`
  The method is still available, but implemented by a super class now.
- Removed super interface Iterable from ConfigurationSectionContainer.
  Instead Iterable, Collection is now used. That is a compatible change: expanding the interface set.

Maybe you can check that?

**Comment by cruftex** [comment]
@lvc Hi Andrey,

thanks for looking into this.

The best way would be to take the JDK sources into account as well, so this works correctly without manual intervention.

In any case the report is very irritating. It needs to be corrected or we need to disable it.

If there is no way that the report is doing this automatically correctly at the moment, I would like that we remove cache2k from the report generation. Its too time consuming to inspect the output for correctness and make individual counter measures. That slows me down.

**Comment by cruftex** [comment]
Closing here. Please reopen/ping if there are some improvements.
