### ISSUE TITLE
Add increment support

### ISSUE THREAD

**Issue by quaff** [cache2k/cache2k#75]
Please provide built-in increment operation, here is my solution, I'm not sure it's atomic. 
```	
	public long increment(String key, long delta, int timeToLive, TimeUnit timeUnit, String namespace) {
		Cache<String, Object> cache = getCache(namespace, true);
		CacheEntry<String, Object> ce = cache.invoke(key, e -> {
			if (e.exists()) {
				((AtomicLong) e.getValue()).addAndGet(delta);
			} else {
				e.setValue(new AtomicLong(delta));
			}
			e.setExpiry(System.currentTimeMillis() + timeUnit.toMillis(timeToLive));
			return e;
		});
		return ((AtomicLong) ce.getValue()).get();
	}
```

**Comment by cruftex** [comment]
Your solutions works. Thanks for sharing! Operations with the entry processor are atomic. You don't need to use the `AtomicLong`, just a normal `Long` is sufficient, since the atomic behavior is done by `Cache.invoke`.

> Please provide built-in increment operation

I am very careful to add new operations. Probably there could be thousands of variants of useful cache entry operations. Probably the better solution is to collect usages like above in a separate library.

The only real good reason for built-in solution would be to get rid of the additional overhead. If you have any trouble and/or want to increase performance let me know.

Keeping the issue open. If there are more people asking for built-in increment support, maybe I get confinced ;)

**Comment by quaff** [comment]
Thanks, you have misspelled "convinced".

**Comment by cruftex** [comment]
Corrected ;)

**Comment by cruftex** [comment]
Closing. Better not put this on the main API to keep it small.
